name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-ubuntu-24_04:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - name: Describe build host
      run: |
        uname -a
        gcc --version
        clang --version

    - name: Debug build with GCC
      run: make -j$(nproc) -C src V=1 DEBUG=1

    - name: Release build with GCC
      run: make -j$(nproc) -C src V=1

    - name: Debug build with Clang
      run: make -j$(nproc) -C src V=1 DEBUG=1 CC=clang CXX=clang++ USE_CLANG=1

    - name: Release build with Clang
      run: make -j$(nproc) -C src V=1 CC=clang CXX=clang++ USE_CLANG=1
